version: "2.3"

services:

  wetty:
    # built from Dockerfile
    # image: butlerx/wetty 
    image: mydigitalwalk/wetty:latest
    restart: always
    mem_limit: 300M
    container_name: wetty
#    tty: true
    working_dir: /usr/src/app
    env_file:
      - env-wetty
    environment:
      SSHHOST: 'wetty-ssh'
      SSHPORT: 22
      NODE_ENV: 'production'
      BASEURL: '/manage'
    networks:
      - traefik_proxy
      - default
    volumes:
      - ./data/ssl:/ssl
      - ./data/ssh:/root/.ssh
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=wetty"
      - "traefik.frontend.rule=Host:${DOMAINNAME}"
      - "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"
      - "traefik.protocol=https"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"


  wetty-ssh:
    # built from dockerfile: Dockerfile-ssh
    image: mydigitalwalk/wetty-ssh:latest
    # this is needed so wetty can connect to it
    container_name: 'wetty-ssh'
    restart: always
    mem_limit: 200M
    env_file:
      - env
# Only fill this if you don't use the above 'env' file
#    environment:
#      WETTY_USER: 'YourUser'
#      WETTY_PASSWORD: 'YourPassPhrase'
#      SSHHOST: 'w.x.y.z'
#      SSHPORT: 22
#      SSHUSER: YourSystemUser
    volumes:
      - ./data/sshd:/data
    networks:
      - default
 
networks:
  traefik_proxy:
    external:
      name: traefik_proxy

