version: "2.3"

services:

  wetty:
    # built from Dockerfile
    image: mydigitalwalk/wetty:latest
    # image: butlerx/wetty
    restart: always
    mem_limit: 300M
    container_name: wetty
#    tty: true
    env_file:
      - .env
    environment:
      SSHHOST: 'wetty-ssh'
      SSHPORT: 22
      NODE_ENV: 'production'
    networks:
      - traefik_proxy
      - default
    volumes:
      - wetty-data:/home/node
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=wetty"
      - "traefik.frontend.rule=Host:${DOMAINNAME}"
      - "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"
      - "traefik.protocol=https"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
#    # If you want to build your own image (remember to pull the wetty submodule):
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: wetty
#    # Already in the image, but here too in case you'd like to change it
#    healthcheck:
#      test: [ "CMD", "curl", "--fail", "--insecure", "-sS", "https://localhost:3000/${BASEURL}" ]
#      interval: 30s
#      timeout: 20s
#      retries: 3
#      disable: true


  wetty-ssh:
    # built from Dockerfile-ssh
    image: mydigitalwalk/wetty-ssh:latest
    # this is needed so wetty can connect to it
    container_name: 'wetty-ssh'
    restart: always
    mem_limit: 200M
    env_file:
      - env-wetty-ssh
    volumes:
      - wetty_ssh-data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
#    # If you want to build your own image (remember to pull the wetty submodule):
#    build:
#      context: .
#      dockerfile: Dockerfile-ssh
#    image: wetty-ssh
#    # Image already has this, but you can modify or disable it here.
#    healthcheck:
#      test: [ "CMD", "/healthcheck" ]
#      interval: 30s
#      timeout: 20s
#      retries: 3
#      disable: true

networks:
  traefik_proxy:
    external:
      name: traefik_proxy

volumes:
  wetty-data:
    name: wetty-data
  wetty_ssh-data:
    name: wetty_ssh-data
